
logging.level.com.netflix.hystrix: DEBUG
logging.level.org.springframework.web.client: DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
management.endpoints.web.exposure.include: hystrix.stream